### PR TITLE
Issue 4

### LINKED ISSUE #4: LangSmith Prompts
Produce a set of example prompts and store them in Langsmith.

Produce also an evaluation agent to measure if the agent responds as expected on known indicators.

Links: https://docs.smith.langchain.com/concepts/evaluation

### PR DESCRIPTION
**Pull request by AshfaaqF**
Integrated Langsmith and tested the traces by creating a database of example prompts.

Produced a simple evaluation agent to measure the agent's response.

I will work on creating a database to perform evaluation on the agent with different prompt engineering framework along with issue 5.

### CODE REVIEW

**Comment by priamai** [comment]
This is a good start,
we should save a good sample set of VirusTotal reports for different IOC that we save statically as the context behind the question.
Since mostly any IOC will change his detection rate over time is better to pick some and save them as text.
We should also add a framework such as DSPY: https://github.com/stanfordnlp/dspy/tree/main
To optimize the prompt format.

**Comment by AshfaaqF** [comment]
Awesome ! Will start improving on it.

**Comment by priamai** [comment]
@AshfaaqF can you review the conflict in the run_qa.py file?

**Comment by AshfaaqF** [comment]
Sure, I will do it.

Cheers.
________________________________

**Comment by AshfaaqF** [comment]
The Evaluator function was improved to evaluate the agent's final response only. It iterates the dataset on langsmith and performs evaluation on the agent's responses based on the input. 

I have attached a simple dataset with 20 samples. I am planning to add more samples and perform more evaluation on different prompt frameworks. Please do let me know if there is anything.  

[Virus Total Dataset.csv](https://github.com/user-attachments/files/16502062/Virus.Total.Dataset.csv).

**Comment by priamai** [comment]
This is a good start!

**Pull request merged**
